---
- name: Setup locales
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items:
    - en_US.UTF-8

- name: Set timezone to EST
  timezone:
    name: America/New_York

- name: Add an Apt signing keyfor HashiCorp
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Manage sources.list
  template:
    src: 'etc/apt/sources.list.j2'
    dest: '/etc/apt/sources.list'
    mode: 0644
  notify: update_apt_cache

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install basic packages
  apt:
    update_cache: yes
    state: present
    name:
      - vim
      - git
      - htop
      - curl
      - wget
      - sudo
      - strace
      - zip
      - unzip
      - time
      - apt-utils
      - man-db
      - dnsutils
      - telnet
      - tcpdump
      - lsof
      - ca-certificates
      - logrotate
      - rsyslog
      - net-tools
      - terraform
      - vault
      - consul
      - nomad
      - waypoint

- name: Add rsyslog logrotate without delaycompress
  template:
    src: 'etc/logrotate.d/rsyslog.j2'
    dest: '/etc/logrotate.d/rsyslog'
    mode: 0644

- name: Set swappiness to 0
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: yes